name: Build & Release Binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.18'

      - name: Download Go modules
        run: go mod download

      - name: Build binary
        run: |
          mkdir -p bin # Explicitly create the output directory
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
          go build -v -o bin/modpilot-${{ matrix.goos }}-${{ matrix.goarch }} . # Add -v for verbose output

      - name: Archive binary
        run: |
          mkdir -p dist
          if [ "${{ matrix.goos }}" = "windows" ]; then \
            zip -j dist/modpilot-${{ matrix.goos }}-${{ matrix.goarch }}.zip bin/modpilot-${{ matrix.goos }}-${{ matrix.goarch }}.exe; \
          else \
            tar -C bin -czf dist/modpilot-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz modpilot-${{ matrix.goos }}-${{ matrix.goarch }}; \
          fi

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
